name: test_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.5.0
  cloud_firestore: ^6.1.3
  firebase_auth: ^6.2.0
  image_picker: ^1.2.1
  http: ^1.2.2
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/worldscore_logo.png
    - assets/scorecard.jpeg
    - assets/mock/ocr_response.json
    - assets/worldscore_ad.jpeg
    - assets/rodeo_hole3_blurred.JPG
    - assets/new_logo.jpg

  uses-material-design: true
