// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFr1AfovG3Hn2CaGjT4XmFhh_GmE8YC9Y',
    appId: '1:532888031039:web:51690c9fc899c07df90d8a',
    messagingSenderId: '532888031039',
    projectId: 'worldscore-ai',
    authDomain: 'worldscore-ai.firebaseapp.com',
    storageBucket: 'worldscore-ai.firebasestorage.app',
    measurementId: 'G-1ZJRZ24QXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoVFxBGxCayaK0ytdNvANm6Z3TsAflAP4',
    appId: '1:532888031039:android:382378cd06b3ff42f90d8a',
    messagingSenderId: '532888031039',
    projectId: 'worldscore-ai',
    storageBucket: 'worldscore-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5GBBMiEjA8PhD1_m9zB1K_OcjD_OKE-E',
    appId: '1:532888031039:ios:99595ae2ce638a84f90d8a',
    messagingSenderId: '532888031039',
    projectId: 'worldscore-ai',
    storageBucket: 'worldscore-ai.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5GBBMiEjA8PhD1_m9zB1K_OcjD_OKE-E',
    appId: '1:532888031039:ios:99595ae2ce638a84f90d8a',
    messagingSenderId: '532888031039',
    projectId: 'worldscore-ai',
    storageBucket: 'worldscore-ai.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFr1AfovG3Hn2CaGjT4XmFhh_GmE8YC9Y',
    appId: '1:532888031039:web:0cf89a35af595618f90d8a',
    messagingSenderId: '532888031039',
    projectId: 'worldscore-ai',
    authDomain: 'worldscore-ai.firebaseapp.com',
    storageBucket: 'worldscore-ai.firebasestorage.app',
    measurementId: 'G-EJX9B34V27',
  );
}
